import { Field } from "../types";

export const field: Field = [
  [
    {
      x: 0,
      y: 0,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 0,
      y: 1,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 0,
      y: 2,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 0,
      y: 3,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 0,
      y: 4,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 0,
      y: 5,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 0,
      y: 6,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 0,
      y: 7,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 0,
      y: 8,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 0,
      y: 9,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
  ],
  [
    {
      x: 1,
      y: 0,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 1,
      y: 1,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 1,
      y: 2,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 1,
      y: 3,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 1,
      y: 4,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 1,
      y: 5,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 1,
      y: 6,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 1,
      y: 7,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 1,
      y: 8,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 1,
      y: 9,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
  ],
  [
    {
      x: 2,
      y: 0,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 2,
      y: 1,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 2,
      y: 2,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 2,
      y: 3,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 2,
      y: 4,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 2,
      y: 5,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 2,
      y: 6,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 2,
      y: 7,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 2,
      y: 8,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 2,
      y: 9,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
  ],
  [
    {
      x: 3,
      y: 0,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 3,
      y: 1,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 3,
      y: 2,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 3,
      y: 3,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 3,
      y: 4,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 3,
      y: 5,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 3,
      y: 6,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 3,
      y: 7,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 3,
      y: 8,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 3,
      y: 9,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
  ],
  [
    {
      x: 4,
      y: 0,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 4,
      y: 1,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 4,
      y: 2,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 4,
      y: 3,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 4,
      y: 4,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 4,
      y: 5,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 4,
      y: 6,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 4,
      y: 7,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 4,
      y: 8,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 4,
      y: 9,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
  ],
  [
    {
      x: 5,
      y: 0,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 5,
      y: 1,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 5,
      y: 2,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 5,
      y: 3,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 5,
      y: 4,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 5,
      y: 5,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 5,
      y: 6,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 5,
      y: 7,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 5,
      y: 8,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 5,
      y: 9,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
  ],
  [
    {
      x: 6,
      y: 0,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 6,
      y: 1,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 6,
      y: 2,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 6,
      y: 3,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 6,
      y: 4,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 6,
      y: 5,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 6,
      y: 6,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 6,
      y: 7,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 6,
      y: 8,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 6,
      y: 9,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
  ],
  [
    {
      x: 7,
      y: 0,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 7,
      y: 1,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 7,
      y: 2,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 7,
      y: 3,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 7,
      y: 4,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 7,
      y: 5,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 7,
      y: 6,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 7,
      y: 7,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 7,
      y: 8,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 7,
      y: 9,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
  ],
  [
    {
      x: 8,
      y: 0,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 8,
      y: 1,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 8,
      y: 2,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 8,
      y: 3,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 8,
      y: 4,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 8,
      y: 5,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 8,
      y: 6,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 8,
      y: 7,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 8,
      y: 8,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 8,
      y: 9,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
  ],
  [
    {
      x: 9,
      y: 0,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 9,
      y: 1,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 9,
      y: 2,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 9,
      y: 3,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 9,
      y: 4,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 9,
      y: 5,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 9,
      y: 6,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 9,
      y: 7,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 9,
      y: 8,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
    {
      x: 9,
      y: 9,
      entity: null,
      collision: [0, 0, 0, 0],
      sprite: "",
    },
  ],
];
